devices:
  adjust_period: 10
  capture:
    channels: 2
    device: hw:Loopback,0,0
    format: S32LE
    type: Alsa
  capture_samplerate: 0
  chunksize: 4096
  enable_rate_adjust: false
  enable_resampling: false
  playback:
    channels: 2
    device: hw:Headphones,0,0
    format: S16LE
    type: Alsa
  queuelimit: 4
  rate_measure_interval: 1
  resampler_type: Synchronous
  samplerate: 88200
  silence_threshold: -60
  silence_timeout: 5
  stop_on_rate_change: false
  target_level: 0
filters:
  Vol:
    parameters:
      ramp_time: 200
    type: Volume
mixers: {}
pipeline:
- channel: 0
  names: []
  type: Filter
- channel: 1
  names: []
  type: Filter
