devices:
  adjust_period: 3
  capture:
    channels: 2
    device: hw:Loopback,0,0
    format: S32LE
    type: Alsa
  capture_samplerate: 44100
  chunksize: 2048
  enable_rate_adjust: false
  enable_resampling: false
  playback:
    channels: 2
    device: hw:Headphones,0,0
    format: S16LE
    type: Alsa
  queuelimit: 4
  rate_measure_interval: 1
  resampler_type: Synchronous
  samplerate: 44100
  silence_threshold: -62
  silence_timeout: 5
  stop_on_rate_change: false
  target_level: 1024
filters:
  Bass:
    parameters:
      freq: 85
      gain: 4
      q: 0.9
      type: Lowshelf
    type: Biquad
  Treble:
    parameters:
      freq: 6500
      gain: 2
      q: 0.7
      type: Highshelf
    type: Biquad
  Volume:
    parameters:
      ramp_time: 200
    type: Volume
mixers: {}
pipeline:
- channel: 1
  names:
  - Bass
  - Treble
  - Volume
  type: Filter
- channel: 1
  names:
  - Bass
  - Treble
  - Volume
  type: Filter
