description: '"House" curve created using first order high shelf filters with gain
  -0.7

  Down approx -5.85dB at 10kHz and -6.5 at 20kHz


  For most of us it probably make sense to remove the two first filters at 20Hz and
  40Hz from the pipeline'
devices:
  adjust_period: null
  capture:
    channels: 2
    device: hw:CARD=Loopback,DEV=0
    format: S32LE
    type: Alsa
  capture_samplerate: 44100
  chunksize: 4096
  enable_rate_adjust: false
  playback:
    channels: 2
    device: hw:CARD=Headphones,DEV=0
    format: S32LE
    type: Alsa
  queuelimit: null
  rate_measure_interval: null
  resampler: null
  samplerate: 44100
  silence_threshold: null
  silence_timeout: null
  stop_on_rate_change: null
  target_level: null
  volume_ramp_time: 200
filters:
  Bass:
    description: Bass slider
    parameters:
      freq: 85
      gain: 0
      q: 0.9
      type: Lowshelf
    type: Biquad
  HSFO-10240Hz:
    description: High Shelf First Order
    parameters:
      freq: 10240
      gain: -0.7
      type: HighshelfFO
    type: Biquad
  HSFO-1280Hz:
    description: High Shelf First Order
    parameters:
      freq: 1280
      gain: -0.7
      type: HighshelfFO
    type: Biquad
  HSFO-160Hz:
    description: High Shelf First Order
    parameters:
      freq: 160
      gain: -0.7
      type: HighshelfFO
    type: Biquad
  HSFO-20480Hz:
    description: High Shelf First Order
    parameters:
      freq: 20480
      gain: -0.7
      type: HighshelfFO
    type: Biquad
  HSFO-20Hz:
    description: High Shelf First Order
    parameters:
      freq: 20
      gain: -0.7
      type: HighshelfFO
    type: Biquad
  HSFO-2560Hz:
    description: High Shelf First Order
    parameters:
      freq: 2560
      gain: -0.7
      type: HighshelfFO
    type: Biquad
  HSFO-320Hz:
    description: High Shelf First Order
    parameters:
      freq: 320
      gain: -0.7
      type: HighshelfFO
    type: Biquad
  HSFO-40Hz:
    description: High Shelf First Order
    parameters:
      freq: 40
      gain: -0.7
      type: HighshelfFO
    type: Biquad
  HSFO-5120Hz:
    description: High Shelf First Order
    parameters:
      freq: 5120
      gain: -0.7
      type: HighshelfFO
    type: Biquad
  HSFO-640Hz:
    description: High Shelf First Order
    parameters:
      freq: 640
      gain: -0.7
      type: HighshelfFO
    type: Biquad
  HSFO-80Hz:
    description: High Shelf First Order
    parameters:
      freq: 80
      gain: -0.7
      type: HighshelfFO
    type: Biquad
  Treble:
    description: Treble slider
    parameters:
      freq: 6500
      gain: 0
      slope: 6
      type: Highshelf
    type: Biquad
  Volume:
    description: Main Volume Fader
    parameters:
      attenuate_mid: true
      fader: Main
      high_boost: 5
      low_boost: 5
      reference_level: 0
    type: Loudness
mixers:
  Unnamed Mixer 1:
    channels:
      in: 2
      out: 2
    description: null
    mapping:
    - dest: 0
      mute: false
      sources:
      - channel: 0
        gain: 0
        inverted: false
        mute: false
        scale: dB
pipeline:
- bypassed: false
  channel: 0
  description: null
  names:
  - Volume
  type: Filter
- bypassed: false
  channel: 1
  description: null
  names:
  - Volume
  type: Filter
- bypassed: false
  channel: 0
  description: null
  names:
  - HSFO-20Hz
  - HSFO-40Hz
  - HSFO-160Hz
  - HSFO-320Hz
  - HSFO-640Hz
  - HSFO-1280Hz
  - HSFO-2560Hz
  - HSFO-5120Hz
  - HSFO-10240Hz
  - HSFO-20480Hz
  type: Filter
- bypassed: false
  channel: 1
  description: null
  names:
  - HSFO-20Hz
  - HSFO-40Hz
  - HSFO-160Hz
  - HSFO-320Hz
  - HSFO-640Hz
  - HSFO-1280Hz
  - HSFO-2560Hz
  - HSFO-5120Hz
  - HSFO-10240Hz
  - HSFO-20480Hz
  type: Filter
processors: {}
title: House Filter 0.7
